blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blogs.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

blogs/urls.py
"""Defines URL patterns for Blogs app"""

from django.urls import path

from . import views

app_name = 'blogs'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Displays full blog post
    path('blog_post/<int:post_id>', views.blog_post, name='blog_post'),
    # Create a new blog post
    path('new_post', views.new_post, name='new_post'),
    # Edit blog posts
    path('edit_post/<int:blog_id>/', views.edit_post, name='edit_post'),
]

users/urls.py
"""Defines URL patterns for Users app"""

from django.conf.urls import include
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    # Default auth urls
    path('', include('django.contrib.auth.urls')),
    # Registration
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.db.models.fields import DateTimeField
from django.contrib.auth.models import User

class BlogPost(models.Model):
    """Model for blog post for webapp."""
    title = models.CharField(max_length=255)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        """Return a string representation of the model."""
        return f"{self.text[:150]}..."
        

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost

class BlogForm(forms.ModelForm):
    """Form to create new blog posts."""
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {
            'title': 'Title', 
            'text': ''
        }
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

blogs/views.py
from django.db import reset_queries
import blogs
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.core.paginator import Paginator
from .models import BlogPost
from .forms import BlogForm

def check_post_owner(request, post):
    """Checks if the requesting user is the post owner"""
    if post.owner != request.user:
        raise Http404

def index(request):
    """Home page listing the blogs in chronological order."""
    blogs = BlogPost.objects.all().order_by('-date_added')
    paginator = Paginator(blogs, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'blogs': page_obj}
    return render(request, 'blogs/index.html', context)

def blog_post(request, post_id):
    """Displays individual blog post."""
    blog = BlogPost.objects.get(id=post_id)
    context = {'blog': blog}
    return render(request, 'blogs/blog_post.html', context)

@login_required
def new_post(request):
    """Create a new blog post."""
    if request.method != 'POST':
        # No form has been submitted, create a new one.
        form = BlogForm()
    else:
        # Data submitted, process and save if valid
        form = BlogForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return redirect('blogs:index')

    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)

@login_required
def edit_post(request, blog_id):
    """Edit a blog post."""
    post = BlogPost.objects.get(id=blog_id)
    text = post.text
    title = post.title
    check_post_owner(request, post)

    if request.method != 'POST':
        # Pre-fill with what is saved in the database
        form = BlogForm(instance=post)
    else:
        # Data submitted, validate
        form = BlogForm(instance= post, data= request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blog_post', post_id=post.id)

    # Show a new edit entry form, or an invalidated form
    context = {'title': title, 'text': text, 'post': post, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

users/views.py
from django.http import request
from django.shortcuts import render, redirect

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user."""

    if request.method != "POST":
        form = UserCreationForm()
    else:
        # Process submitted form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Login then redirect to index
            login(request, new_user)
            return redirect('blogs:index')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}
{% load static %}

<!doctype html>
  <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, 
      shrink-to-fit=no">

      <title>The Cool Blog</title>
      
      <meta name="description" content="The coolest blog on the interwebs.">

      {% bootstrap_css %}
      {% bootstrap_javascript jquery='full' %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    </head>

    <body>
      <div class="container-bg">
        <div class="container">
          <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
              <div class="col-6 pt-1">
                <a class="blog-header-logo text-muted font-italic logo-lg" 
                  href="{% url 'blogs:index' %}">
                  The Cool Blog</a>
              </div>
              <div class="col-6 d-flex justify-content-end align-items-center authstyles">
                {% if user.is_authenticated %}
                  <p class="text-muted mr-2 mt-3">Hey, {{ user.username }}.</p> 
                  <a class="btn btn-sm btn-outline-danger" 
                    href="{% url 'users:logout' %}">Log out</a>
                {% else %}
                  <a class="btn btn-sm btn-outline-primary mr-2" 
                    href="{% url 'users:login' %}">Log in</a>
                  <a class="btn btn-sm btn-outline-secondary" 
                    href="{% url 'users:register' %}">Register</a>
                {% endif %}
              </div>
            </div>
          </header>
          <div class="nav-scroller py-1">
            <nav class="nav d-flex justify-content-between">
              <a class="p-2 text-muted" href="{% url 'blogs:index' %}#coolin">
                Checkin' the day
              </a>
              <a class="p-2 text-muted" href="#">Cool</a>
              <a class="p-2 text-muted" href="#">Cooler</a>
              <a class="p-2 text-muted" href="#">Coolest</a>
            </nav>
          </div>
        </div>
      </div>

      
      <div class="border-bottom">
        {% block jumbotron %}{% endblock jumbotron %}
      </div>

      <main role="main" class="container">
        <div class="pb-2">
          {% block page_header %}{% endblock page_header %}
        </div>
        
        <div class="mx-auto">
          {% block content %}{% endblock content %}
        </div>

        <button type="button" class="btn btn-danger btn-floating btn-lg p-1" 
          id="btn-back-to-top"><img src="static/img/To-Top-Arrow.svg" width="36px" height="36px"></button>
        </main>
        
        <div class="p-4 m-4">
          <footer class="page-footer font-small fixed-bottom">
            <p class="footer-copyright py-3 text-center">Copyright "The Cool", 20XX</p>
          </footer>
        </div>
      
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>

  </html>

blogs/templates/blogs/blog_post.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <h3 class="display-3">{{ blog.title }}</h3>
{% endblock page_header %}

{% block content %}
  <div class="container">
    <p class="font-italic text-muted">
      by {{ blog.owner }}
      <br>
      {{ blog.date_added|date:'M d, Y h:i A e'}}
    </p>

    <p class="p-2 px-md-3 lead">
      {{ blog.text|linebreaks }}
    </p>

    {% if blog.owner == user %}
      <a class="btn btn-outline-warning btn-sm"
        href="{% url 'blogs:edit_post' blog.id %}">Edit Post</a>
    {% endif %}
  </div>

{% endblock content %}

blogs/templates/blogs/edit_post.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
  <h3 class="display-4">Editing post: {{ blog.title }}</h3>
{% endblock page_header %}

{% block content %}
  <form class="form" action="{% url "blogs:edit_post" post.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
  </form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block jumbotron %}
  <div class="jumbotron p-4 p-md-5 text-white rounded cool-bg">
    <div>
      <h4 class="display-4 banner">
        Home of the coolest news around town, man.
      </h4> 
    </div>
  </div>
{% endblock jumbotron %}

{% block content %}
  {% if user.is_authenticated %}
  <div class="mt-3 mb-3">
    <a class="btn btn-primary btn-sm" 
      href="{% url 'blogs:new_post' %}">Add a new post</a>
  </div>
  {% endif %}
  
  <h4 class="display-4" id="coolin">What's Coolin'</h4>
  <dl>
    {% for blog in blogs|slice:'0:9' %}
      <dd>
        <dt>{{ blog.title }}, {{ blog.date_added|date:'M d, Y h:i A e'}}</dt>
        <dd class="lead">{{ blog.text|slice:'0:100' }}...</dd>
        <a class="btn btn-outline-primary btn-sm" href="{% url 'blogs:blog_post' blog.id %}">Read More</a>
        
        <hr>
      </dd>
    {% empty %}
      <p class="lead">Sorry, there have been no blog posts added yet. </p>
    {% endfor %}
  </dl>

  <div class="container p-3 m-auto text-center">
    <span class="current">
      <p>Page {{ blogs.number }} of {{ blogs.paginator.num_pages }}</p>
    </span>
    <nav class="blog-pagination">
      <span class="step-links">
        {% if blogs.has_previous %}
          <a class="btn btn-outline-info" href="?page=1">&laquo; First</a>
          <a class="btn btn-outline-info" href="?page={{ blogs.previous_page_number }}">Newer</a>
        {% endif %}
        

        {% if blogs.has_next %}
          <a class="btn btn-outline-info" href="?page={{ blogs.next_page_number }}">Older</a>
          <a class="btn btn-outline-info" href="?page={{ blogs.paginator.num_pages }}">Last &raquo;</a>
        {% endif %}
      </span>
    </nav>

  </div>

{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
  <h3 class="display-4">New Post</h3>
{% endblock page_header %}

{% block content %}
  <form class="form" action="{% url 'blogs:new_post' %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit" class="btn btn-primary">Post</button>
    {% endbuttons %}
  </form>

{% endblock content %}